# Generated by Django 3.2.7 on 2021-09-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0003_remove_cleaning_cleaningtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='employee',
            field=models.CharField(default=1, max_length=60, verbose_name='Employee Name'),
            preserve_default=False,
        ),
    ]
