# Generated by Django 3.2.7 on 2021-09-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0004_cleaning_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaning',
            name='location',
        ),
        migrations.AddField(
            model_name='cleaning',
            name='apt',
            field=models.CharField(choices=[('APT 01', 'APT 01'), ('APT 02', 'APT 01'), ('APT 03', 'APT 03')], default=1, max_length=10, verbose_name='Apartment'),
            preserve_default=False,
        ),
    ]
