# Generated by Django 3.2.7 on 2021-09-11 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
