<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genre',
            field=models.CharField(choices=[('Masculine', 'Masculine'), ('Feminine', 'Feminine'), ('Do not inform', 'Do not inform')], max_length=60),
        ),
    ]
=======
# Generated by Django 3.2.7 on 2021-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genre',
            field=models.CharField(choices=[('Masculine', 'Masculine'), ('Feminine', 'Feminine'), ('Do not inform', 'Do not inform')], max_length=60),
        ),
    ]
>>>>>>> 7ecf0588ac716eb8e28267220c531014cd74540b
