# Generated by Django 3.2.7 on 2021-09-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20210911_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='value',
            field=models.CharField(max_length=9, verbose_name='Value'),
        ),
    ]
