# Generated by Django 3.2.7 on 2021-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_check_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Cleaning', 'Cleaning')], max_length=10)),
                ('location', models.CharField(choices=[('APT 01', 'APT 01'), ('APT 02', 'APT 01'), ('APT 03', 'APT 03')], max_length=10)),
                ('cleaningtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
