<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-09-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cleaning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cleaning',
        ),
    ]
=======
# Generated by Django 3.2.7 on 2021-09-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cleaning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cleaning',
        ),
    ]
>>>>>>> 7ecf0588ac716eb8e28267220c531014cd74540b
