# Generated by Django 3.2.7 on 2021-09-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_check_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Name'),
        ),
    ]
